### PR TITLE
add logging capability

### PR DESCRIPTION
**Pull request by arrucard**
Hi 

From some time I am struggling with cors issues and I could not trace what is the problem. It looks like from time to time requests are rejected by cors. I would like to add some logging to have more informations about failing requests. Please check it and let me know what are you thinking about it.

Regards,
Bartek

### CODE REVIEW

**Comment by davidtinker** [comment]
Tx. I will do a release tonight with your changes.

**Comment by davidtinker** [comment]
This is in 1.2.0. The Plugin portal notification failed when I published it so its not listed on grails.org/plugins.

**Comment by arrucard** [comment]
Wow, ultra fast response:D 
Why it failed? Something wrong with changes?

**Comment by davidtinker** [comment]
I think the service that updates the portal when plugins are published is
down.

**Comment by arrucard** [comment]
oh, ok :) thanks

**Pull request merged**
